spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/auth
    username: root
    password: password
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true

redis:
  server:
    urls: redis://localhost:6379

jwt:
  accessToken:
    expiration:
      time: 15
  refreshToken:
    expiration:
      count: 50
      time: 21600

crypt:
  algorithm:
    message-digest: SHA-256
    aes: AES
  token-secret-key: a
  global-salt: app-global-salt

  client:
    ms-user:
      endpoint: http://localhost:8000

server:
  port: 8082
